Vr lesson 3
AlexJavaGuru/java_1_tuesday_jan_23 pull request #10
Opened 2023-02-03 19:59 UTC by WladislawRomanow

2023-02-04 17:50 UTC, AlexJavaGuru requested changes
Очень плохо переменные называете

2023-02-04 17:50 UTC, AlexJavaGuru commented on src/main/java/student_vladislav_romanov/lesson_3/level_7/Car.java
> +        this.setModel(model);
когда инициализируем объект, мы не используем методы (супер редко, и это должно быть оправданно). Просто присвойте значения через =

2023-02-04 17:50 UTC, AlexJavaGuru commented on src/main/java/student_vladislav_romanov/lesson_3/level_7/CarDemo.java
> +        // Print car information
Комменты лишние

2023-02-04 17:50 UTC, AlexJavaGuru commented on src/main/java/student_vladislav_romanov/lesson_3/level_7/CarDemo.java
> +        System.out.println(car1.getColor() + " " + car1.getType() + " " + car1.getModel() + " " + car1.getYear());
Может лучше создать метод printInformation для нашей машины? Где она всё покажет на консоль? Будет на много красивее

2023-02-04 17:50 UTC, AlexJavaGuru commented on src/main/java/student_vladislav_romanov/lesson_3/level_7/CarDemo.java
> +        Car car1 = new Car("BMW 528", "Blue", 2015, 86000, 238);
car1? может можно подумать над более хорошими названиями

2023-02-04 17:50 UTC, AlexJavaGuru commented on src/main/java/student_vladislav_romanov/lesson_3/level_7/Planet.java
> +        int distanceFromSolarToEarth = 149500000;
у любой планеты будет одно и то же расстояние для земли?

2023-02-04 17:50 UTC, AlexJavaGuru commented on src/main/java/student_vladislav_romanov/lesson_3/level_7/Planet.java
> +        int distanceFromSolarToEarth = 149500000;
Лучше сделать из этого глобальную переменную. На лекции покажу как.

2023-02-04 17:50 UTC, AlexJavaGuru commented on src/main/java/student_vladislav_romanov/lesson_3/level_7/Planet.java
> +        return this.name;
тут можно не использовать this. т.к. нет конфликта имён.

2023-02-04 17:50 UTC, AlexJavaGuru commented on src/main/java/student_vladislav_romanov/lesson_3/level_7/PlanetDemo.java
> +        Planet planet1 = new Planet("Earth", 12.756,149500000, true, false);
почему переменные planet1? Вам же самому не удобно потом читать код...с этими числами. Используйте нормальные названия - earth, venus, jupiter

2023-02-04 17:50 UTC, AlexJavaGuru commented on src/main/java/student_vladislav_romanov/lesson_3/level_7/ProductDemo.java
> +        Product product1 = new Product("Desktop PC");
Такая же проблема с названием переменных

2023-02-04 18:47 UTC, WladislawRomanow commented on src/main/java/student_vladislav_romanov/lesson_3/level_7/Car.java
> +        this.setModel(model);
А в каких случаях это будет оправданным?

2023-02-04 19:25 UTC, WladislawRomanow commented
Переделал согласно комментариям.

2023-02-04 19:27 UTC, WladislawRomanow commented on src/main/java/student_vladislav_romanov/lesson_3/level_7/Planet.java
> +        isStar = true;
Посмотрел, что метод же просто превращает планету в звезду, а значит можно не передавать переменную true, сразу же писать это в теле сеттера.

2023-02-08 20:11 UTC, AlexJavaGuru approved these changes
Посмотрите комментарий про Circle

2023-02-08 20:11 UTC, AlexJavaGuru commented on src/main/java/student_vladislav_romanov/lesson_3/level_7/Circle.java
> +    double calculateArea(double radius) {
В метод calculateArea не должно приходить ничего. Сигнатура должны быть: double calculateArea() {
У метода уже будет доступ к значению (к своему состоянию)

2023-02-08 20:12 UTC, merged