AC_lesson_4
AlexJavaGuru/java_1_tuesday_jan_23 pull request #27
Opened 2023-02-13 15:36 UTC by AndrejsCekalins

2023-02-16 21:49 UTC, AlexJavaGuru requested changes
number_input надо переименовать везде. Плохое название для сканера.

2023-02-16 21:49 UTC, AlexJavaGuru commented on src/main/java/student_andrejs_cekalins/lesson_4/level_1/Task_2.java
> +        Scanner number_input = new Scanner(System.in);
_ не мы не используем в джаве для названия переменных.

2023-02-16 21:49 UTC, AlexJavaGuru commented on src/main/java/student_andrejs_cekalins/lesson_4/level_1/Task_3.java
> +        Scanner number_input = new Scanner(System.in);
Название переменной

2023-02-16 21:49 UTC, AlexJavaGuru commented on src/main/java/student_andrejs_cekalins/lesson_4/level_1/Task_2.java
> +        Scanner number_input = new Scanner(System.in);
Еще numberInput не характеризует то, что переменная хранит. Хранит она не инпут, а сканер.

2023-02-16 21:49 UTC, AlexJavaGuru commented on src/main/java/student_andrejs_cekalins/lesson_4/level_6/StockTest.java
> +class StockTest {
Это не тест. Это просто демо. Напишите нормальные тесты.

2023-02-16 21:49 UTC, AlexJavaGuru commented on src/main/java/student_andrejs_cekalins/lesson_4/level_7/Task_23/LeapYearTest.java
> +class LeapYearTest {
ну как минимум надо еще проверить, что метод возвращает другое булево значение

2023-02-16 21:49 UTC, AlexJavaGuru commented on src/main/java/student_andrejs_cekalins/lesson_4/level_7/Task_24/Calculator.java
> +        return firstNumber / secondNumber;
Вы забыли про приведение типа (double)

2023-02-20 11:48 UTC, AndrejsCekalins commented on src/main/java/student_andrejs_cekalins/lesson_4/level_7/Task_24/Calculator.java
> +        return firstNumber / secondNumber;
Александр, не понял комментария, про: (double)

2023-02-22 18:53 UTC, AlexJavaGuru approved these changes

2023-02-22 18:53 UTC, AlexJavaGuru commented on src/main/java/student_andrejs_cekalins/lesson_4/level_1/Task_2.java
> +        Scanner number = new Scanner(System.in);
Все еще не понимаю логику названия переменной. Почему number то? Это же сканер!

2023-02-22 18:53 UTC, AlexJavaGuru commented on src/main/java/student_andrejs_cekalins/lesson_4/level_6/Stock.java
> +    int initialPrice;
Зря переименовали. По логике это как раз был currentPrice

2023-02-22 18:53 UTC, merged