Og lesson 3
AlexJavaGuru/java_1_tuesday_jan_23 pull request #33
Opened 2023-02-15 12:31 UTC by Evroleg

Lesson 3

2023-02-18 19:34 UTC, AlexJavaGuru requested changes

2023-02-18 19:34 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/_lesson_3/TrafficLightControlsTheCar.java
> +public class TrafficLightControlsTheCar {
Что это? )))

2023-02-18 19:34 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/_lesson_3/level_1_3/Robot.java
> +class Robot {
Ужасный формат. Ничего не понятно. Есть определённый порядок в класе
- состояния 
- конструкторы
- методы

У вас тут все в кашу.

2023-02-18 19:34 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/_lesson_3/level_5/Dog.java
> +class Dog {
Формат на уровне класса. Используйте Ctrl + Alt + L

2023-02-18 19:34 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/_lesson_3/level_5/Dog.java
> +        if (n > 0) {
n? из названия должен быть понятен смысл.

2023-02-18 19:34 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/_lesson_3/level_5/Dog.java
> +        newAge += age;
мы должны установить состояние age в новое значение (логично просто увеличить age на 1...

2023-02-18 19:34 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/_lesson_3/level_5/Dog.java
> +    String[] color = {"Red", "Black", "Orange","Green"};
зачем это? Переменных в этой части класса быть не должно.

2023-02-18 19:34 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/_lesson_3/level_5/Dog.java
> +    String[] changeColor(int i) {
почему смена цвета возвращает массив?

2023-02-18 19:34 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/_lesson_3/level_5/Dog.java
> +        System.out.println("And I'am " + color[i] + " now.");
Где сама смена цвета? Зачем выводить на консоль то, чего даже не случилось? Собака то цвет не поменяла. Состояние объекта не изменилась.

2023-02-18 19:34 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/_lesson_3/level_5/Dog.java
> +        return color.clone();
Сами не используйте метод clone. Логика должна писаться без использования подобных методов.

2023-02-18 19:34 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/_lesson_3/level_7/Circle.java
> +public class Circle {
Это должен быть класс, описывающий состояние radius. Это состояние мы инициализируем при создании объекта (подаем в конструктор), а затем, в методе calculateArea (который ничего принимать не должен), мы считаем площадь. 
square разве площадь?

2023-02-18 19:34 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/_lesson_3/level_7/Product.java
> +public class Product {
Задание не доделано

2023-02-18 19:34 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/_lesson_3/level_7/Product.java
> +    public void setRegularPrice(double regP) {
не regP а regularPrice

2023-02-18 19:34 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/_lesson_3/level_7/Product.java
> +    public void setDiscount(double disC) {
не disC а dicsount

2023-02-18 19:34 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/_lesson_3/level_7/Product.java
> +    Product(String computer) {
Почему переменная называется computer? мы ничего другого не ожидаем ?

2023-02-18 19:34 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/_lesson_3/level_7/Product.java
> +    String computer;
что за переменная?

2023-02-18 19:34 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/lesson_4/level_1/DifferentTasks.java
> +class DifferentTasks {
что вы пишите? К чему этот класс?

2023-02-18 19:34 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/lesson_4/level_1/DifferentTasks.java
> +    static int a;
Я вам уже говорил на тему статических состояний у класса. Состояние опять тут и опять название просто одна буква...

2023-02-18 19:34 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/lesson_4/level_1/DifferentTasks.java
> +
Я вам рекомендую удалить весь этот класс. Вы не тем занимаетесь, чем нужно.

2023-02-19 08:29 UTC, Evroleg commented on src/main/java/student_oleg_gryazev/_lesson_3/TrafficLightControlsTheCar.java
> +public class TrafficLightControlsTheCar {
Dvizenije avtomobilja v zavisimosti ot signala svetofora

2023-02-19 09:02 UTC, Evroleg commented on src/main/java/student_oleg_gryazev/_lesson_3/level_5/Dog.java
> +        newAge += age;
A kak delatj izmenenija?  tut v Gite?

2023-02-19 18:25 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/_lesson_3/level_5/Dog.java
> +        newAge += age;
делайте в вашем бранче. Для которого открыт этот ПР. Мы это обсуждали на лекции. Найти вам видео?

2023-02-19 18:25 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/_lesson_3/TrafficLightControlsTheCar.java
> +public class TrafficLightControlsTheCar {
Где у нас такое задание?

2023-02-22 08:37 UTC, Evroleg commented on src/main/java/student_oleg_gryazev/_lesson_3/TrafficLightControlsTheCar.java
> +public class TrafficLightControlsTheCar {
Lesson 3 level 7, task 29 
Выберите два разных объекта из реального мира.
Для каждого объекта выделите 2 - 3 самых важных
свойства и поведения, которое с этими свойствами
связано. Создайте для каждого объекта из реального
мира Java класс с его описанием. Создайте так же
Demo класс для каждого описанного вами объекта
и продемонстрируйте работу с объектом.

2023-02-22 08:50 UTC, Evroleg commented on src/main/java/student_oleg_gryazev/lesson_4/level_1/DifferentTasks.java
> +class DifferentTasks {
Peredelal

2023-02-22 08:51 UTC, Evroleg commented on src/main/java/student_oleg_gryazev/lesson_4/level_1/DifferentTasks.java
> +    static int a;
peredelal

2023-02-22 08:51 UTC, Evroleg commented on src/main/java/student_oleg_gryazev/lesson_4/level_1/DifferentTasks.java
> +
peredelal

2023-02-22 08:56 UTC, Evroleg commented on src/main/java/student_oleg_gryazev/_lesson_3/level_7/Product.java
> +    String computer;
peredelal

2023-02-22 08:57 UTC, Evroleg commented on src/main/java/student_oleg_gryazev/_lesson_3/level_5/Dog.java
> +        newAge += age;
peredelal

2023-02-22 18:59 UTC, AlexJavaGuru commented
Ничего не переделано. Все еще ошибки.

2023-03-29 17:57 UTC, AlexJavaGuru approved these changes
Я заапрувлю, но у меня всё еще большие вопросы к вашему коду.

2023-03-29 17:57 UTC, merged