Vr lesson 5
AlexJavaGuru/java_1_tuesday_jan_23 pull request #37
Opened 2023-02-17 19:37 UTC by WladislawRomanow

2023-02-20 23:08 UTC, AlexJavaGuru requested changes

2023-02-20 23:08 UTC, AlexJavaGuru commented on src/main/java/student_vladislav_romanov/lesson_5/extra/TicTacToe.java
> +    public boolean isWinPositionForHorizontals(char[][] field, char playerToCheck) {
В чем смысл этого counter? Может мы можем упростить весь метод, идя от обратного? Проверять, ячейка за ячейкой -> если встретили != PlayerTocheck, то можем сразу выйти с false. Если цикл завершился -> возвращать true. Было бы на много меньше кода.

2023-02-20 23:08 UTC, AlexJavaGuru commented on src/main/java/student_vladislav_romanov/lesson_5/extra/TicTacToe.java
> +    public boolean isWinPositionForDiagonals(char[][] field, char playerToCheck) {
Такие методы писать плохо. Метод решает сразу две задачи. Можно было бы разбить его на 2 отдельных, а потом вызывать в этом методе эти два отдельных через ||

2023-02-20 23:08 UTC, AlexJavaGuru commented on src/main/java/student_vladislav_romanov/lesson_5/extra/TicTacToe.java
> +        int counter = 0;
опять эти counter-s нагрузили вашу логику очень сильно.

2023-02-20 23:08 UTC, AlexJavaGuru commented on src/main/java/student_vladislav_romanov/lesson_5/level_2/Task_14.java
> +        System.out.println(arraySum / numbers.length);
(double) ?

2023-02-21 08:46 UTC, WladislawRomanow commented
Александр, спасибо за подсказки! Я сам себя изначально заморочил, что необходимо будет играть в крестики-нолики по 3 элемента на поле размера больше чем 3х3. Оттого и счётчики вставил. Вариант с булевыми переменными выглядит читабельнее. 

Я переделал методы со счётчиков на булевы переменные. И разделение проверки диагоналей на 2 разных метода ещё больше упростило саму проверку диагоналей.

Поправил проблему с (double) и ещё несколько файлов из level_4 и level_7 чтобы Java11 не ругалась (правки с рабочего компа делаю, а там только 8 и 11 стоит).

2023-02-22 19:03 UTC, AlexJavaGuru approved these changes

2023-02-22 19:03 UTC, AlexJavaGuru commented on src/main/java/student_vladislav_romanov/lesson_5/extra/TicTacToe.java
> +            boolean winPosition = true;
Был бы вообще топ, если вы уберёте этот флаг. Он вообще не нужен.

2023-02-22 19:03 UTC, AlexJavaGuru commented on src/main/java/student_vladislav_romanov/lesson_5/extra/TicTacToe.java
> +                    winPosition = false;
тут можно сразу вернуть false

2023-02-22 19:03 UTC, AlexJavaGuru commented on src/main/java/student_vladislav_romanov/lesson_5/extra/TicTacToe.java
> +        return false;
а тут true

2023-02-22 19:03 UTC, merged

2023-02-23 06:40 UTC, WladislawRomanow commented on src/main/java/student_vladislav_romanov/lesson_5/extra/TicTacToe.java
> +                    winPosition = false;
Так если тут вернуть сразу false, то он ведь не будет пробегать по остальным рядам. Там где перебор в одном цикле (диагонали) я так и сделал, работает отлично и код красивый, а вот тут я себе уже голову сломал.