Nr lesson 4
AlexJavaGuru/java_1_tuesday_jan_23 pull request #38
Opened 2023-02-17 20:03 UTC by NatalijaNovel

Задания Stock and Leap Year остаются за мной в долгу, не могу с ними подружиться пока.

2023-02-22 21:01 UTC, AlexJavaGuru requested changes
Надо поправить. Пишите в чате, если не понятно, что нужно сделать

2023-02-22 21:01 UTC, AlexJavaGuru commented on src/main/java/student_natalija_rasponomarjova/lesson_4/level_7/Calculator.java
> +class Calculator {
Зачем вы написали в класс с тестами калькулятор? Разделите. Тем более, что калькулятор уже в левел 4 написан у вас

2023-02-22 21:01 UTC, AlexJavaGuru commented on src/main/java/student_natalija_rasponomarjova/lesson_4/level_7/FizzBuzz.java
> +        if (isDividedBy3(number) && number % 5 != 0) {
Используйте if else if. Не надо писать отдельные условия. Мы хотим выйти, как только хоть какие-то условие даст true, нам не надо больше ничего проверять

2023-02-24 18:28 UTC, NatalijaNovel commented
Саша привет! А по поводу первого коммента ("Надо поправить. Пишите в чате, если не понятно, что нужно сделать") - это касается комментариев по заданиям?  Или еще что-то надо поправить?

2023-02-24 18:29 UTC, NatalijaNovel commented on src/main/java/student_natalija_rasponomarjova/lesson_4/level_3/Task_10.java
> +        max = number1;
зачем-то хочется усложнять:)))

2023-02-24 22:48 UTC, AlexJavaGuru commented
Это Я на счет всех комментов

2023-02-24 22:49 UTC, AlexJavaGuru approved these changes

2023-02-24 22:49 UTC, merged