Konstantin Kudrjavtsev: Lesson 2: Homework
AlexJavaGuru/java_1_tuesday_jan_23 pull request #39
Opened 2023-02-17 20:32 UTC by Qnikiart

2023-02-22 21:03 UTC, AlexJavaGuru commented
Верните мне в папку файл - [Task_0.txt]

2023-02-22 21:20 UTC, AlexJavaGuru requested changes
Все хорошо, только бы файлы мне мои вернуть

2023-02-22 21:36 UTC, Qnikiart commented
Если можешь подскажи. Я думаю так, новый бранч сделать и из своей папки в
папку teacher, затем на github commit и push?
Lesson 3 дошёл до github?

ср, 22 февр. 2023 г., 23:21 AlexJavaGuru ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Все хорошо, только бы файлы мне мои вернуть
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AlexJavaGuru/java_1_tuesday_jan_23/pull/39#pullrequestreview-1310253736>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5JZ3OBACJG5LXLA5YYFNNLWYZ7L7ANCNFSM6AAAAAAU727G6M>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-03-03 18:11 UTC, Qnikiart commented
java: constructor Stock in class
student_konstantin_kudrjavtsev.lesson_4.level_6_middle.Stock cannot be
applied to given types;
  required: java.lang.String,int
  found:    no arguments
  reason: actual and formal argument lists differ in length

в консоли это написано

2023-03-09 18:49 UTC, AlexJavaGuru submitted a review, later dismissed

2023-03-09 18:56 UTC, merged