AL lessons 3 home work
AlexJavaGuru/java_1_tuesday_jan_23 pull request #5
Opened 2023-01-31 20:44 UTC by AlexandrLezh

Please check my homework.

2023-02-01 18:58 UTC, AlexJavaGuru requested changes

2023-02-01 18:58 UTC, AlexJavaGuru commented on src/main/java/student_aleksandrs_lezhennikovs/lesson_3/level_7/Shop.java
> +    boolean shopOpenStatus;
isOpen

2023-02-01 20:50 UTC, AlexandrLezh commented on src/main/java/student_aleksandrs_lezhennikovs/lesson_3/level_5/Dog.java
> +    String dogsColor;
fixed

2023-02-01 20:51 UTC, AlexandrLezh commented on src/main/java/student_aleksandrs_lezhennikovs/lesson_3/level_7/Shop.java
> +    String shopName;
fixed

2023-02-01 20:51 UTC, AlexandrLezh commented on src/main/java/student_aleksandrs_lezhennikovs/lesson_3/level_7/Shop.java
> +    boolean shopOpenStatus;
fixed

2023-02-02 20:15 UTC, AlexJavaGuru approved these changes

2023-02-02 20:15 UTC, merged