Og lesson 4
AlexJavaGuru/java_1_tuesday_jan_23 pull request #52
Opened 2023-02-22 08:27 UTC by Evroleg

Lesson 4 level 1-10

2023-02-22 15:53 UTC, Evroleg reviewed
Ne poluchajetsa pull request

2023-02-24 22:46 UTC, AlexJavaGuru requested changes

2023-02-24 22:46 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/lesson_4/level_1_10/ArithmeticOperation.java
> +public class ArithmeticOperation {
что это за задание?

2023-02-24 22:46 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/lesson_4/level_1/DifferentTasks.java
> +class DifferentTasks {
Почему это всё еще здесь?

2023-02-24 22:46 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/lesson_4/level_1_10/ArithmeticOperation.java
> +    static int firstNumber;
статических состояний тут быть не должно.

2023-02-24 22:46 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/lesson_4/level_1_10/ArithmeticOperation.java
> +    void negativePositiveOrZero() {
Все методы должны работать с параметрами, которые подаются в методы, а не со статическими состояниями.

2023-02-24 22:46 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/lesson_4/level_5/LightColorDetector.java
> +            System.out.println("Blue");
Можно убрать вывод на консоль. Это тут лишнее. Пусть тот, кто вызывает метод, сам решает, что делать с результатом.

2023-02-24 22:46 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/lesson_4/level_5/LightColorDetector.java
> +    int wavelength;
это состояние тут не нужно.

2023-02-24 22:46 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/lesson_4/level_5/LightColorDetector.java
> +    void testVisibleSpectrum() {
тестов не должно быть в классе с основной логикой

2023-02-24 22:46 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/lesson_4/level_7_task24/Calculator.java
> +class CalculatorTest {
Вынести тесты в отдельный класс

2023-02-24 22:46 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/lesson_4/level_7_task24/Calculator.java
> +    public static void main(String[] args) {
Каждый тестовый сценарий должен быть в отдельном методе.

2023-03-02 10:41 UTC, Evroleg commented on src/main/java/student_oleg_gryazev/lesson_4/level_1_10/ArithmeticOperation.java
> +    void negativePositiveOrZero() {
Dobrij dernj Aleksandr, razve sushestvujushaj struktura ne sootvetstvujet OOP? Klass Arith. operation soderzit metodi, Klass switch pereklichajet metodi v zavisimosti ot postsvlennih zadach v raspechativajemom menu. Argumenti podajutsa so scanera v parametri e.g. firstNumber = scanner.nextInt();
Esli ne tak to vchom moja oshibka? Hochu ponjatj.

2023-03-04 22:37 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/lesson_4/level_1_10/ArithmeticOperation.java
> +    void negativePositiveOrZero() {
Ошибка в том, что вы пытаетесь сделать какой-то универсальный класс, который решит все ваши проблемы (в данном случае задания). Это не то, чему я стараюсь вас научить. Вы просто игнорируете обычный clean code принцип. Класс должен отвечать за одну задачу, если это возможно. В вашем случае, это возможно. Я уже на уроке прокомментировал ваш подход к решению задач. Почему мы всё еще про это разговариваем? Вы способны сделать задание так, как от вас ожидают? или нет?

2023-03-04 22:39 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/lesson_4/level_1_10/ArithmeticOperation.java
> +    void negativePositiveOrZero() {
До ООП в этих заданиях нам еще далеко. Я уже написал вам, как это должно быть написано. Методы должны принимать аргументы для работы, а не использовать статические состояния.

2023-03-17 22:32 UTC, AlexJavaGuru approved these changes

2023-03-17 22:32 UTC, AlexJavaGuru commented on src/main/java/student_oleg_gryazev/lesson_4/level_1_10/ArithmeticOperation.java
> +        int firstNumber = typeInOneDigit();
Конечно хотелось бы чтобы аргументы приходили в метод, но уже не желания с вами бороться

2023-03-17 22:32 UTC, merged