Ac lesson 7
AlexJavaGuru/java_1_tuesday_jan_23 pull request #70
Opened 2023-03-09 20:02 UTC by AndrejsCekalins

2023-03-17 21:09 UTC, AlexJavaGuru requested changes

2023-03-17 21:09 UTC, AlexJavaGuru commented on src/main/java/student_andrejs_cekalins/lesson_7/level_7/Task_15_16/UsersRepository.java
> +class UsersRepository {
А где метод addUser? И это репозиторий должен следить за ID и увеличивать её. Сам UserEntity об этом знать не должен

2023-03-17 21:09 UTC, AlexJavaGuru commented on src/main/java/student_andrejs_cekalins/lesson_7/level_7/Task_15_16/UserEntity.java
> +    private int id = 0;
не стоит сразу присваивать значение в состояния.

2023-03-18 09:10 UTC, AndrejsCekalins commented on src/main/java/student_andrejs_cekalins/lesson_7/level_1/WordService.java
> +    // Counting each word. How meany times it is appearing in array:
Это я для себя шпаргалку на будущее сделал :), пока каша от всей информации в голове.

2023-03-22 19:18 UTC, merged