Vr lesson 7
AlexJavaGuru/java_1_tuesday_jan_23 pull request #74
Opened 2023-03-11 16:55 UTC by WladislawRomanow

2023-03-17 21:34 UTC, AlexJavaGuru requested changes

2023-03-17 21:34 UTC, AlexJavaGuru commented on src/main/java/student_vladislav_romanov/lesson_7/level_1/WordService.java
> +    private String[] split;
а зачем состояния? Это только усложнит использование этого функционала. Я как пользователь, хочу просто вызвать метод у утилиты и получить результат. Зачем мне создавать объект для этого? и еще что-то сетать туда?

2023-03-17 21:34 UTC, AlexJavaGuru commented on src/main/java/student_vladislav_romanov/lesson_7/level_6/ArrayCopy.java
> +    int[] fillTemporaryArray(int[] trim, int number) {
Это ооочень не оптимальное решение. Каждый раз вы будете переписывать все числа в новый массив. Если у вас будет 1 000 000 элементов? это очень много лишних операций. Лучше всего посчитать 1 раз, сколько таких чисел, потом создать нужный массив и переписать туда все числа.

2023-03-17 21:34 UTC, AlexJavaGuru commented on src/main/java/student_vladislav_romanov/lesson_7/level_6/CreditCard.java
> +            setBalance(debtAfterWithdraw - debt);
зачем для этого вызывать внутренние методы? Можно сразу сделать this.balance = debtAfterWithdraw - debt;

2023-03-17 21:34 UTC, AlexJavaGuru commented on src/main/java/student_vladislav_romanov/lesson_7/level_6/CreditCard.java
> +class CreditCard {
Очень много подметодов. Довольно сложно читать.

2023-03-17 21:34 UTC, AlexJavaGuru commented on src/main/java/student_vladislav_romanov/lesson_7/level_6/CreditCard.java
> +class CreditCard {
но это исправлять не надо. Это скорее общий фидбек

2023-03-17 21:34 UTC, AlexJavaGuru commented on src/main/java/student_vladislav_romanov/lesson_7/level_7/UserEntity.java
> +        id = ++idBase;
За присвоение id должен отвечать репозиторий а не сам объект пользователя.

2023-03-17 21:34 UTC, AlexJavaGuru commented on src/main/java/student_vladislav_romanov/lesson_7/level_7/WordService.java
> +    String[] textArray;
Я бы избавился от состояний в классе. Он может спокойно работать с входящими параметрами в методы

2023-03-19 14:03 UTC, WladislawRomanow commented on src/main/java/student_vladislav_romanov/lesson_7/level_6/CreditCard.java
> +class CreditCard {
Просто говорилось, что лучше максимально атомизировать код на методы, вот я и вынес максимально каждую операцию.

2023-03-19 14:07 UTC, WladislawRomanow commented
Откорректировал согласно комментариям.

2023-03-22 19:27 UTC, AlexJavaGuru approved these changes

2023-03-22 19:27 UTC, merged