Vb lesson 3
AlexJavaGuru/java_1_tuesday_jan_23 pull request #8
Opened 2023-02-02 20:31 UTC by behman89

2023-02-02 20:41 UTC, AlexJavaGuru requested changes

2023-02-02 20:41 UTC, AlexJavaGuru commented on src/main/java/student_vlad_behman/Lesson_3/level_5/Dog.java
> +    public String newColor;
Точно нигде не подглядывали? Я где-то видел уже такое состояние. Оно не нужное.

2023-02-02 20:41 UTC, AlexJavaGuru commented on src/main/java/student_vlad_behman/lesson_3/level_1/Robot.java
> -public class Robot {
Зачем вы удаляете этот класс? Он больше не нужен?

2023-02-02 20:41 UTC, AlexJavaGuru commented on src/main/java/student_vlad_behman/lesson_3/level_1/Robot.java
> -public class Robot {
А, может вы просто делали наперед и решили удалить после последней лекции?

2023-02-02 21:48 UTC, behman89 commented on src/main/java/student_vlad_behman/lesson_3/level_1/Robot.java
> -public class Robot {
ne udolal

2023-02-02 21:48 UTC, behman89 commented on src/main/java/student_vlad_behman/Lesson_3/level_5/Dog.java
> +    public String newColor;
podumal cot sozdav novuju peremenuju budet proshe.

2023-02-02 21:49 UTC, behman89 commented on src/main/java/student_vlad_behman/lesson_3/level_1/Robot.java
> -public class Robot {
na perked mote bit ja nemogu ponjatj nemnogo

2023-02-04 17:16 UTC, AlexJavaGuru approved these changes

2023-02-04 17:16 UTC, merged