AL lesson 9 home work
AlexJavaGuru/java_1_tuesday_jan_23 pull request #88
Opened 2023-03-22 19:59 UTC by AlexandrLezh

Please check.

2023-04-03 20:46 UTC, AlexJavaGuru commented
84? =(

2023-04-07 19:48 UTC, AlexJavaGuru requested changes
Я понял откуда столько классов ) Вы под каждый метод сделали сервис. Это перебор ) Это можно не фиксить, чтобы время не терять, но так не надо

2023-04-07 19:48 UTC, AlexJavaGuru commented on src/main/java/student_aleksandrs_lezhennikovs/lesson_9/level_3/task_10/InMemoryDatabase.java
> +            Optional<Product> optProduct = Optional.ofNullable(product);
Тут я бы чуть-чуть переделал. лучше просто сравнивать через if, и если нашли объект, то вернуть его через return Optional.of(product). Нам совсем не обязательно оборачивать в Optional, чтобы сравнивать объекты.

2023-04-07 19:48 UTC, AlexJavaGuru commented on src/main/java/student_aleksandrs_lezhennikovs/lesson_9/level_5/services/AddService.java
> +public class AddService {
Я бы не разделял на вашем месте сервисы. У вас должны быть разные Actions, но все они должны были вызывать просто разные методы одного сервиса. Дробить т.н. CRUD операции над объектами на отдельные сервисы это слишком много классов лишних.

2023-04-07 19:48 UTC, AlexJavaGuru commented on src/main/java/student_aleksandrs_lezhennikovs/lesson_9/level_5/domain/BookEntity.java
> +    public BookEntity(String title, String author) {
у нас есть порядок элементов в классах. Состояния -> Конструкторы -> Методы

2023-04-07 19:48 UTC, AlexJavaGuru commented on src/main/java/student_aleksandrs_lezhennikovs/lesson_9/level_5/storage/BookReaderImpl.java
> +        if (allChecks(book)) {
allChecks -> validate было бы лучше

2023-04-07 19:48 UTC, AlexJavaGuru commented on src/main/java/student_aleksandrs_lezhennikovs/lesson_9/level_7/task_27/MyListBasedOnLinkedLinkedLIst.java
> +    private LinkedList<Orders> storage = new LinkedList<>();
Используйте интерфейс List<Orders> storage = new LinkedList<>();

2023-04-07 19:48 UTC, AlexJavaGuru commented on src/main/java/student_aleksandrs_lezhennikovs/lesson_9/level_7/task_27/MyListBasedOnLinkedLinkedLIst.java
> +    private Orders searchTitle(String title) {
Почему не объединить в один метод с searchByTitle?

2023-04-08 07:25 UTC, AlexandrLezh commented on src/main/java/student_aleksandrs_lezhennikovs/lesson_9/level_5/services/AddService.java
> +public class AddService {
А как же Single responsibility principle?

2023-04-08 08:13 UTC, AlexandrLezh commented on src/main/java/student_aleksandrs_lezhennikovs/lesson_9/level_3/task_10/InMemoryDatabase.java
> +            Optional<Product> optProduct = Optional.ofNullable(product);
fixed

2023-04-08 08:13 UTC, AlexandrLezh commented on src/main/java/student_aleksandrs_lezhennikovs/lesson_9/level_5/domain/BookEntity.java
> +    public BookEntity(String title, String author) {
fixed

2023-04-08 08:13 UTC, AlexandrLezh commented on src/main/java/student_aleksandrs_lezhennikovs/lesson_9/level_5/storage/BookReaderImpl.java
> +        if (allChecks(book)) {
fixed

2023-04-08 08:13 UTC, AlexandrLezh commented on src/main/java/student_aleksandrs_lezhennikovs/lesson_9/level_7/task_27/MyListBasedOnLinkedLinkedLIst.java
> +    private LinkedList<Orders> storage = new LinkedList<>();
fixed

2023-04-08 08:15 UTC, AlexandrLezh commented on src/main/java/student_aleksandrs_lezhennikovs/lesson_9/level_7/task_27/MyListBasedOnLinkedLinkedLIst.java
> +    private Orders searchTitle(String title) {
я как раз его разделил, думал читабельность будет лучше, но там опять появился return null O_o.
Вообщем вернул обратно в один метод.

2023-04-08 20:14 UTC, AlexJavaGuru approved these changes

2023-04-08 20:15 UTC, merged